seed_everything: null
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: bird-classification
      log_model: all
      save_dir: /app/output/wandb
  checkpoint_callback: null
  enable_checkpointing: true
  callbacks: null
  default_root_dir: /app/output/pl
  gradient_clip_val: null
  gradient_clip_algorithm: null
  process_position: 0
  num_nodes: 1
  num_processes: null
  devices: null
  gpus: null
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 500
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  flush_logs_every_n_steps: null
  log_every_n_steps: 50
  accelerator: gpu
  strategy: null
  sync_batchnorm: false
  precision: 16
  enable_model_summary: true
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: null
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  prepare_data_per_node: null
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
  terminate_on_nan: null
model:
  num_classes: 400
  learning_rate: 0.002
  lr_reduce_factor: 0.1
  lr_reduce_patience: 10
  early_stop_patience: 30
data:
  data_dir: /app/input/dataset/birds-400
  batch_size: 256
  shuffle: true
  num_workers: 56
  pin_memory: false
ckpt_path: null
